version: '3'
services:
  postgresql:
    image: postgres
    container_name: my-postgresql-container
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DATABASE}
