version: '3'
services:
  postgresql:
    image: postgres
    container_name: todoList
    ports:
      - '5433:5432'
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: todoList
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-todoList
    ports:
      - '6379:6379'
