version: '3'
services:
  postgresql:
    image: postgres
    container_name: my-postgresql-container
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ['postgres', '-c', 'log_statement=all']
  redis:
    image: redis:alpine3.14
    container_name: my-redis-container
    ports:
      - '6379:6379'
